repos:
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.4.3
    hooks:
      - id: american-eg-ie
      - id: cleveref-capitalization
      - id: consistent-spelling
        args:
            [
              "--emph=et al.",
              "--emph=a priori",
              "--emph=a posteriori",
              '--regex=naive=\bna(i|\\"i)ve',
            ]
      - id: csquotes
      - id: ensure-labels-for-sections
      - id: no-space-in-cite
      - id: tilde-cite
      - id: unique-labels
      - id: cleveref-instead-of-autoref
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        files: ".*\\.(?:tex|py)$"